spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    defer-datasource-initialization: true

db:
  mysql:
    url: jdbc:mysql://localhost:3306/lottery?createDatabaseIfNotExist=false&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: mypassword123